### ISSUE TITLE
Unable to connect as master

### ISSUE THREAD

**Issue by kumar-ashish1** [akshat7101999/WebRTC-scalable-broadcast-p2p#1]
Hi i am running this on localhost and using in 2 different chrome tabs all are working fine but don't know how to connect as master .

**Comment by akshat7101999** [comment]
Hello Ashish
The first tab that you open is the master's . Every subsequent tab that you open will be of the client that will relay the master's feed. In Readme.md, i have mentioned it in the fourth point.

**Comment by kumar-ashish1** [comment]
ok thanks it solved . i want to ask does it support mobile browsers ? bcoz getting problem in iPhone safari.

**Comment by akshat7101999** [comment]
Yes, you are right this is not working on safari. On android chrome, the mobile browser is able to listen to the coming stream but unable to forward it. There may be some limitations in hardware itself but i am not sure. It works great with nodes as PC's or laptops. You can close the issue if resolved.
